version: "3.8"

services:
  dns-exporter:
    environment:
      DNS_SERVERS: 62.138.222.111,62.138.222.222
      TEST_DOMAINS: debian.org,debian.com,s3.de-west-1.psmanaged.com,asfzgasfuzgasf.frfef
      SLEEP_INTERVAL: 0.5
    build: .
    container_name: dns_exporter
    ports:
      - "8000:8000"
    restart: unless-stopped
