version: "3.8"

services:
  dns-exporter:
    environment:
      DNS_SERVERS: 8.8.8.8,1.1.1.1,9.9.9.9
      TEST_DOMAINS: example.com,google.com
      SLEEP_INTERVAL: 1
    build: .
    container_name: dns_exporter
    ports:
      - "8000:8000"
    restart: unless-stopped
