# DNS Exporter Deployment & Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-exporter
  labels:
    app: dns-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-exporter
  template:
    metadata:
      labels:
        app: dns-exporter
    spec:
      containers:
        - name: dns-exporter
          image: ghcr.io/keyboardinterrupt/dns_exporter/dns_exporter:latest
          ports:
            - containerPort: 8000
          env:
            - name: DNS_SERVERS
              value: "8.8.8.8,1.1.1.1.222,9.9.9.9"
            - name: TEST_DOMAINS
              value: "debian.org,debian.com,example.com"
            - name: SLEEP_INTERVAL
              value: "0.5"

---
apiVersion: v1
kind: Service
metadata:
  name: dns-exporter
spec:
  selector:
    app: dns-exporter
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP # Expose only internally within the cluster

