name: Test DNS Exporter Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.11', '3.12', '3.13']  # Test with multiple Python versions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run DNS Exporter script
      run: |
        python3 dns_exporter.py &
        # Give the script time to start up
        sleep 10

    - name: Test if the Prometheus metrics endpoint is working
      run: |
        curl --silent --fail http://localhost:8000/metrics | grep "dns_response_avg_seconds_"

    - name: Stop the script
      run: |
        pkill -f dns_exporter.py
